name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: /home/runner/work/node-app/node-app

    - name: Run build script
      run: npm run build
      working-directory: /home/runner/work/node-app/node-app

    - name: Create artifacts directory
      run: mkdir -p /home/runner/work/node-app/node-app/artifacts

    - name: Move build artifacts
      run: cp -r /home/runner/work/node-app/node-app/build/* /home/runner/work/node-app/node-app/artifacts/
      working-directory: /home/runner/work/node-app/node-app

    - name: Build Docker image
      run: docker build -t nodejs-sample-app .
      working-directory: /home/runner/work/node-app/node-app/artifacts

    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name nodejs-sample-app nodejs-sample-app
      working-directory: /home/runner/work/node-app/node-app/artifacts

