name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: node-app

    - name: Run tests
      run: npm test
      working-directory: node-app

    - name: Build Docker image
      run: docker build -t hello-world-app ./node-app

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name hello-world-app hello-world-app
        sleep 10
        curl -I http://localhost:3000

